cstart.o = $(TEST_DIR)/cstart.o
bits = 32
ldarch = elf_i386

cflatobjs += lib/x86/setjmp32.o

tests = $(TEST_DIR)/taskswitch.flat $(TEST_DIR)/taskswitch2.flat \
	$(TEST_DIR)/cmpxchg8b.flat

tests-realmode = $(TEST_DIR)/realmode/rmode_sample.flat

tests += $(tests-realmode)

include $(SRCDIR)/$(TEST_DIR)/Makefile.common
